on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo rm -f /etc/apt/sources.list.d/*google-chrome*
      - run: sudo rm -f /etc/apt/sources.list.d/*microsoft*
      - run: sudo apt-get update
